### ISSUE TITLE
Pagination links styling

### ISSUE THREAD

**Issue by kingfisher13** [axismaps/axis-jekyll#10]
Bottom of each blog page (not post, but the actual page).

**Comment by bcsheesley** [comment]
I don't see this anymore, but maybe a bigger size version of the "How we handle data", "How we design" links from the Home page would work (using the Axis blue color).

**Comment by kingfisher13** [comment]
Ready for you to check it @bcsheesley.

**Comment by bcsheesley** [comment]
I'm still not seeing these. Are they supposed to sit below the metadata when viewing a single post? For me, the metadata is at the very bottom, with only our copyright info below, but I may be confused about what we're talking about.

**Comment by kingfisher13** [comment]
@bcsheesley Bottom of the [blog index page](http://axismaps.github.io/axis-jekyll/blog/). Sorry for not being more clear.

**Comment by bcsheesley** [comment]
Looks good to me! Can we add pagination to the individual blog post pages, too? If so, maybe something like this?

"Share this" should be #777 and the other headers should match.

![pagination 2](https://cloud.githubusercontent.com/assets/4501388/10959088/2cfbaa06-833a-11e5-8dc0-6e966bd59304.png)

**Comment by bcsheesley** [comment]
Actually, our live site has spacing between the metadata and pagination buttons. That would be okay to leave in. We could remove the gray and just have the background texture there.

![cartography_with_an_actual_blindfold___axis_maps_blog](https://cloud.githubusercontent.com/assets/4501388/10959167/fde83cf6-833a-11e5-97e9-9012186f8a1c.png)
