### ISSUE TITLE
Social media and metadata styling

### ISSUE THREAD

**Issue by kingfisher13** [axismaps/axis-jekyll#11]
Bottom of each blog post.

**Comment by kingfisher13** [comment]
@bcsheesley I matched the old site styles with these. Let me know what needs to change.

**Comment by kingfisher13** [comment]
@davidheyman The WP site has Category and Author index pages. Jekyll can't auto-generate these as its static. There are 2 ways around it if we want to link to those from each individual blog post's metadata.
1. A single page of all the (e.g.) Author posts sorted by author, and then jump-points at the beginning of each author. Then we just link to that jump-point.
2. [Detailed here](http://christianspecht.de/2014/10/25/separate-pages-per-tag-category-with-jekyll-without-plugins/), we essentially create a static page that relies on a dynamically generated template. Downside, we have to create a page for **each** Category and Author.

or 3. We don't link the Author and Category, just list them as general information. This is the current setup.

**Comment by bcsheesley** [comment]
I'm okay with #3. I actually wouldn't mind removing Category and just listing date and author, but could go either way. (Our categories seem pretty general / obvious.)

In terms of styling, the metadata text can be Rosario 18px, #777. That background color should be #eee:

![meta](https://cloud.githubusercontent.com/assets/4501388/10896849/3dd7af00-8182-11e5-9745-469a7f2b82b1.png)

**Comment by davidheyman** [comment]
Me too. Let’s just remove category since I don’t think it’s always applicable or if people really care.

**Comment by kingfisher13** [comment]
Do we care about number of Tweets/Likes/Pluses?

**Comment by bcsheesley** [comment]
Personally, I would say it doesn't matter. Besides Andy's most recent D3 post, looks like the numbers tend to be pretty small if not zero.
