### ISSUE TITLE
H1 styling on blog post

### ISSUE THREAD

**Issue by kingfisher13** [axismaps/axis-jekyll#12]
On an individual blog post (not the index page), the h1 styling is different from the index page. Should it match?

See:
http://axismaps.github.io/axis-jekyll/blog/
http://axismaps.github.io/axis-jekyll/cartography/2015/06/18/cartography-with-an-actual-blindfold.html

**Comment by bcsheesley** [comment]
Yeah, they should match. It should look the way it does on the index page currently, which is Rosario 700, 36px, #fff.
