### ISSUE TITLE
Home page text styles

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#16]
It helped me to go through and assign styles to this text so I could see it better. Let me know if any of the annotations don't make sense. I'm sure there will be a few more tweaks here after this.

![home](https://cloud.githubusercontent.com/assets/4501388/10944742/3b559508-82e0-11e5-92c2-3c3124143054.png)

**Comment by kingfisher13** [comment]
@bcsheesley Couple things here:
1. H2 and H3. What specifically would you like changed here? Changing the html tag messes up a bunch of stuff. Easier for me to just manually adjust the size if that's what you were wanting.
2. Navigation color. Did you want `#555`? Or was that supposed to be the `background-color`?
3. The change to the body font size messed up some heights. Specifically, the png's for the Data/Design/Code expansion. Can I get new version's at 600px tall?

**Comment by bcsheesley** [comment]
1. Data, Design, and Code should be Rosario Bold, 30px, #333. The ribbon text should be Rosario Bold Italic 24px, #fff with enough line height to give it breathing room... maybe 60px? 

The gray color of the ribbon itself should change to #999.
1. Yeah, let's go with #555 for the nav text.
2. I'll get you those pngs a bit later today, hopefully.

**Comment by bcsheesley** [comment]
Here are those new images for data, design, and code. Data and Design have two options. Use whichever you think looks better. There is also a newly sized image for the interactive maps section.

Data option1
![data2](https://cloud.githubusercontent.com/assets/4501388/10973322/8fcfb65a-83a2-11e5-8539-356d8d22dd19.png)

Data option2
![data](https://cloud.githubusercontent.com/assets/4501388/10973320/8bf111b4-83a2-11e5-913d-03e84797f47d.png)

Design option1
![design](https://cloud.githubusercontent.com/assets/4501388/10973325/93a77a7e-83a2-11e5-84c1-09359e25a47b.png)

Design option2
![design2](https://cloud.githubusercontent.com/assets/4501388/10973328/96fd1c56-83a2-11e5-9199-64228eeb95a2.png)

Code
![code](https://cloud.githubusercontent.com/assets/4501388/10973332/99e2e45a-83a2-11e5-890c-28c41a541ce3.png)

Maps
![maps](https://cloud.githubusercontent.com/assets/4501388/10973334/9cbffa6e-83a2-11e5-9db7-db873922c3c5.png)

**Comment by davidheyman** [comment]
@bcsheesley Can you edit this message and annotate which image is which?
