### ISSUE TITLE
Sidebar text

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#18]
This should be 15/21 expo-serif-pro, #555, like in the image attached. I think it might currently be getting overridden? Also, can we reduce the space between headers and text by 10px?

![screen_shot_2015-11-04_at_7_33_17_pm](https://github-cloud.s3.amazonaws.com/assets%2F4501388%2F10957866%2F28dba5f4-832e-11e5-8142-140031aabe51.png)

**Comment by kingfisher13** [comment]
@bcsheesley See how that looks. Gap was in `ems` (1.3) so I put it at 10px instead.

**Comment by bcsheesley** [comment]
That looks good to me for the gap. It looks like the text size is still too small though. It should be 15px, not 13px. Thanks.
