### ISSUE TITLE
Add an image for the banner spot in the Guide

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#26]
@awoodruff do you have a bigger version of the current banner image? Looks like we'd need 975x360, but the height could be less.

![banner](https://cloud.githubusercontent.com/assets/4501388/10958615/c23edfd4-8335-11e5-8eb8-a30195d1b54b.png)

**Comment by awoodruff** [comment]
@bcsheesley Following up on this after forever. I don't seem to have a bigger version of that banner, nor remember if I created it or if it already existed somewhere. I could try to re-create it, but I bet you could make something prettier!
