### ISSUE TITLE
Text link style

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#4]
This would match the font and size of the intro or body text, depending on where it is.

• Color should be #111
• Dotted bottom border
• Solid bottom border on hover

**Comment by bcsheesley** [comment]
Thanks. Now that I see it, can we make these tweaks?

• Dashed instead of dotted
• Dashed color is #999
• Solid color is also #999

**Comment by kingfisher13** [comment]
What color should the Portfolio links be? Ditto the links on the main page and the company page?

**Comment by bcsheesley** [comment]
Let's go with "Axis blue" for the Porfolio links and "Data", "Design", "Code" links:
#57a1d7
#333 (hover)

Let's go with almost black for the small sidebar links, keeping the dashed and solid (hover) border as-is:
#111

![axis_maps](https://cloud.githubusercontent.com/assets/4501388/10896236/3633cc56-817e-11e5-8ba5-791992a648f4.png)

**Comment by kingfisher13** [comment]
@bcsheesley So should the default link style be the `#111`, `dashed border`, etc... throughout the site? For example, the links in the footer, the links in the tweets bar, the links in the contact form, etc... Or leave those as is?

**Comment by bcsheesley** [comment]
Let's see how it looks making that the default link style for all those.

**Comment by bcsheesley** [comment]
Cool. The only place I don't think it works as well is on image thumbs, like those for indiemapper and ColorBrewer. Can we use the default style for text links only?
