### ISSUE TITLE
Project image captions are positioned relative to window bottom, not image

### ISSUE THREAD

**Issue by awoodruff** [axismaps/axis-jekyll#44]
The caption sticks to the bottom of the window as it's resized.

![screen shot 2015-12-09 at 3 44 03 pm](https://cloud.githubusercontent.com/assets/3533462/11698294/ddb32a9c-9e8b-11e5-92b4-fd340583e57e.png)

**Comment by kingfisher13** [comment]
Caption also goes behind the currently selected image:

![image](https://cloud.githubusercontent.com/assets/9831929/14045613/8597e384-f269-11e5-92f1-b180516aca34.png)
