### ISSUE TITLE
Larger 'view the map' link

### ISSUE THREAD

**Issue by davidheyman** [axismaps/axis-jekyll#49]
I'd really like to direct people here wherever possible but I think this needs a little more oomph. Maybe a icon to go with it?

<img width="732" alt="napkin 04-25-16 1 58 22 pm" src="https://cloud.githubusercontent.com/assets/791434/14784474/c6a66688-0aed-11e6-8131-76206a539758.png">

**Comment by davidheyman** [comment]
@bcsheesley We've got access to all of these icons -> http://fontello.com

Maybe a sweet globe or something?

**Comment by bcsheesley** [comment]
Agreed. I like the globe idea... maybe try the FontAwesome globe in Axis-blue? Although, a straight-up button might even do a better job as far as getting noticed and being easy to click:

![globe](https://cloud.githubusercontent.com/assets/4501388/14857919/9565c63c-0c63-11e6-8dc9-3c9e3f34adf9.png)

![button](https://cloud.githubusercontent.com/assets/4501388/14857923/9a0d83a0-0c63-11e6-89cd-f9a9de55a870.png)
