### ISSUE TITLE
Expanded guide topics

### ISSUE THREAD

**Issue by awoodruff** [axismaps/axis-jekyll#52]
Drawing from that [workshop](http://axismaps.io/crash-course/), this is the list of things on my mind, but anything you guys want to add or remove or change or whatever is great. Just listing everything here even though some pages already exist.
### General map design
- What is a map? / Types of maps
- Types of thematic maps (overview plus a page per type)
- General map design
- Visual variables
- Hierarchy
- Color
- Data classification
- Data normalization
- Scale and generalization
- Projections and coordinate systems
- Text and labels
### Geographic data
- Geographic phenomena (abrupt-smooth etc.)
- Levels of measurement
- Basics of geographic data (vector vs raster etc)
- Data formats (pages on shapefile, geojson, etc.)
- Geocoding
- Data sources
- Working with data (some kind of overview or how-to of typical data tasks)
### Making maps with GIS

Not quite sure how to structure this, but want to provide some kind of overview or tour of what GIS is, what it can do, and a typical mapping workflow. We had some [slides](http://axismaps.io/crash-course/#51) that simply mention a few things in a QGIS workflow but mostly relied on an actual live demo for explaining them. But a full-on tutorial is probably too much; there are better resources for that.
### Interactive and web maps
- What is a web map? (and generally how do they work)
- General interactive design
- UI design or something

Haven't fully thought through web maps. General design topics are good, and then I think there's room for quasi-technical explanations of what web maps are. And pointing out common tools, libraries, etc., but again no need to do actual tutorials on this site.
### Resources!

Migrate the big ol' (and growing) resource list that currently lives at http://axismaps.io/crash-course/resources.html. The idea is to categorize resources by the particular topics covered here. Maybe also include the links on the specific article pages.

**Comment by davidheyman** [comment]
I've migrated the remaining topics over to Basecamp where we can track progress on individual articles there.
