### ISSUE TITLE
Tweaks to page nav and sidebar

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#54]
I'm wondering about a slightly revised page navigation design that might help better organize and draw attention to certain pages. Two possible changes:
- Call out the guide with a guidepost icon.
- Align the the store link on the right-hand side, also with an icon.

Might also be nice to draw attention to the guide in the sidebar, with some brief text and an image. Maybe it could slot in below the Blog and Twitter feeds...

![home](https://cloud.githubusercontent.com/assets/4501388/15435035/aa34ef7e-1e7f-11e6-90d1-e6bfeff866e2.png)

![guide](https://cloud.githubusercontent.com/assets/4501388/15435132/1cebf94a-1e80-11e6-88d2-a990455f9c60.png)

**Comment by awoodruff** [comment]
On a somewhat related note, is there a better name for this thing than a "guide"? I'm not sure it would be at all apparent what a button called "Guide" mean—I might think it's like a guide to the website (remember "site maps"?) or something.

**Comment by davidheyman** [comment]
I was thinking either "learning" or "education" but there could be others.
I was also thinking that various Brewers and indiemapper would sit here as
well. What do you think?

**Comment by bcsheesley** [comment]
"Guidebook" also comes to mind. I like the sound of something practical and helpful as opposed to something passive or academic. As far as the mapmaking tools, I can see those grouped under a "Tools" dropdown or maybe even listed out as links in a different style on a second line. To me, they are on a somewhat different level than our regular page navigation.

**Comment by davidheyman** [comment]
I’d be up for having a “tools” section that could include those plus a link
to our repos on Github.
