### ISSUE TITLE
On mobile, Projects ⬇️ should fit on its own line

### ISSUE THREAD

**Issue by davidheyman** [axismaps/axis-jekyll#64]
I'd shrink the logo first then the title to make it fit

![realios_iPhone_6S](http://static.gitscout.com/7979cf7497300f9956839067dbf84ad903dbec2f4ced407ab9cb6e05b7af5471.jpg)

**Comment by davidheyman** [comment]
In fact I think it's no problem if the header / logo remains a consistent size on mobile

**Comment by bcsheesley** [comment]
Projects ⬇️ is now hidden on mobile because the video is no longer full screen. There should be enough content visible below to indicate scrolling.
