### ISSUE TITLE
Top part of tag line can get cut off on short windows 

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#69]
Not sure what to do about this. Seems a particular problem when in landscape mode on mobile.

- Does adding some responsive height styles make sense? Maybe just for landscape mode?

![window_and_axis_maps](https://user-images.githubusercontent.com/4501388/29326616-dd96ef3e-81b1-11e7-9b1e-fd8d960b9977.png)

**Comment by davidheyman** [comment]
I’d say instead of displaying the full height header, just show it at it’s smaller size (like after it’s been scrolled down). I think the logo is too big anyway for small screens.

**Comment by awoodruff** [comment]
Switched to smaller fixed header on short windows, and also shrank the h1 text a bit, but now that I look at it again I didn't really solve anything beyond like 5px past the breakpoint. I'll mess with it more. (Though this really only affects stupidly short desktop windows now so it's not urgent.)
