### ISSUE TITLE
Home page jacked up on reasonably sized phones

### ISSUE THREAD

**Issue by davidheyman** [axismaps/axis-jekyll#78]
Here's what the home page looks like on my not ridiculously gigantic iPhone SE:

![File Aug 15, 10 47 36 PM](http://static.gitscout.com/bca264986b35274dc3744c8746d8eb270f0136a258b8d39cb5014f223071f835.png)

**Comment by awoodruff** [comment]
This should be decent down to a height of 475px now; not sure what the lower end of "reasonable" is for phones these days.
(This is the same fix for #69 but with some bonus shrinking of text.)
