### ISSUE TITLE
Make the About content one column on narrow-ish windows

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#81]
Maybe switch over at the 850px break point?

![screen shot 2017-08-17 at 11 08 15 am](https://user-images.githubusercontent.com/4501388/29422044-8e7eac20-833c-11e7-900c-506f97f2dcdb.png)

**Comment by awoodruff** [comment]
Switched to center-aligned block image at the 850px break point
![screen shot 2017-08-25 at 4 23 15 pm](https://user-images.githubusercontent.com/3533462/29731251-bd668afa-89b1-11e7-939e-47b82c4afc35.png)
