### ISSUE TITLE
About page headings on mobile

### ISSUE THREAD

**Issue by bcsheesley** [axismaps/axis-jekyll#83]
The numbered headings could use some padding between them and the images. On the other hand, how much of a pain is it to move the headings above the images for each section? Would that make more sense?

![img_1402](https://user-images.githubusercontent.com/4501388/29422861-20f72dbe-833f-11e7-9b57-68c90139b2c4.jpg)

**Comment by awoodruff** [comment]
Moving the headings above probably is a pain, but I've added a 15px margin between them and the image, at least. Hopefully good enough?
